### ISSUE TITLE
about feature

### ISSUE THREAD

**Issue by jun0wanan** [madeleinegrunde/AGQA_baselines_code#1]
hi,

     How to get  video feature ? We should get them by ourselves ? Thank you for your best work!

Best,
J(●'◡'●)

**Comment by madeleinegrunde** [comment]
Hi,

The features are available here: https://drive.google.com/drive/u/0/folders/1c51H6rxGHcc8en_sboFxH7Oqb_SVb2oQ

**Comment by jun0wanan** [comment]
> Hi,
> 
> The features are available here: https://drive.google.com/drive/u/0/folders/1c51H6rxGHcc8en_sboFxH7Oqb_SVb2oQ

hi, your video is tgif-qa ? What about charades ?~

Thansks !

**Comment by jun0wanan** [comment]
where is strID2numID.json feature ? hope to get your help ! Thanks!

**Comment by Buzz-Beater** [comment]
Having the same issue with strID2numID, it seems we can not generate it on our own since the keys to ".h5" files are already indexed by that.

**Comment by madeleinegrunde** [comment]
Thank you for alerting me. I have uploaded this file here: https://drive.google.com/uc?export=download&id=1RwvxZ3r_yguo8C1huLp8osyYyCO-7Gsx

**Comment by jun0wanan** [comment]
hi,

      Why you not  give us  val  dataset ? Should we split by us ?

Best,
wishes

**Comment by madeleinegrunde** [comment]
Thank you for reaching out. Each of the 3 models we used split the val dataset so we used their methods. We adjusted so that no questions from the same video would be in both the training and the validation set.
