### ISSUE TITLE
AGQA_scene_graphs

### ISSUE THREAD

**Issue by yanan1989** [madeleinegrunde/AGQA_baselines_code#10]
Hi,
Thanks for your great work. I can not load "AGQA_test_stsgs.pkl" and "AGQA_train_stsgs.pkl" files. Could you please check and share the code to open them? 

Thank you very much!

**Comment by madeleinegrunde** [comment]
Hi Yanan,

Thanks for reaching out! I have checked, and I am able to upload with the
following Python code.

with open(FILE_PATH, 'rb') as f:
    stsgs = pickle.load(f)

I think the 'rb' argument may be giving you trouble. If this still has
issues please let me know!

All the best,
Madeleine

**Comment by yanan1989** [comment]
Hi Madeleine,

Thanks for your so quick respnse. I've tried as you said. However, I failed in the memory error even with 500G RAM. I am wondering the file is too large to load. Could you please check if you could load [AGQA_test_stsgs.pkl](https://drive.google.com/file/d/1CXU0tWpv-1kkkwkNzpU-BwQoAazPR1kR/view?usp=sharing) and what is your load time and memory assumptions?  

Thank you for your time!
Best,
Yanan

**Comment by madeleinegrunde** [comment]
Hi Yanan,

Hmm it is a large file so the memory may be an issue. For me it takes
approximately 5 seconds to load into a jupyter notebook and the Memory says
1.17 GB for that process.

What is the memory error message you receive? If necessary, I can send you
scene graphs individually as smaller files as well.

Best,
Madeleine

**Comment by yanan1989** [comment]
Thank you Madeleine! 

I think I found the cause of my failure. Beause I've tried to print the loaded scene graph at once. I will study the data format later.
Sorry for your time! Thank you so much!

Best,
Yanan

**Comment by madeleinegrunde** [comment]
Great! The scene graph structure is somewhat complex, so if it is helpful
there is a description of the structure at the bottom of the README
<https://drive.google.com/drive/folders/1OMqA90VXY3BQorKFK5xWLSEEkqX31ui->.

All the best,
Madeleine
