### ISSUE TITLE
what does the number mean?

### ISSUE THREAD

**Issue by LemonQC** [madeleinegrunde/AGQA_baselines_code#11]
As is shown is figure, I found [Unbalanced AGQA](https://downloads.cs.stanford.edu/vision/agqa/AGQA_unbalanced.zip) with 192M questions is not 71G.
![image](https://user-images.githubusercontent.com/30914380/191677399-4e558464-4d29-4447-87bf-4bb533d068e6.png)

**Comment by madeleinegrunde** [comment]
Hi LemonQC,

I am unable to see the image. Could you please try reopening? Thanks!

**Comment by madeleinegrunde** [comment]
Reuploading*

**Comment by LemonQC** [comment]
@madeleinegrunde  My network has some errors and I reuploaded.

**Comment by madeleinegrunde** [comment]
I see it now! How large is the file you downloaded?

**Comment by LemonQC** [comment]
It's about 2.06G

![image](https://user-images.githubusercontent.com/30914380/191677885-dbbeabdf-e4e2-4745-acf4-0b3f120d200c.png)

**Comment by LemonQC** [comment]
They are txt.
![image](https://user-images.githubusercontent.com/30914380/191678064-df55741a-ecca-4bee-9e16-68a2cac8e4cb.png)

**Comment by madeleinegrunde** [comment]
Ah ok I see. The zip file is just 2.1 GB to make it easier to store. The unzipped folder is a collection of txt files. If the questions for all videos were stored in one text file, it would take an extremely long time to load the data. Therefore, we split the data into smaller files (test_all_X.txt). If you add up the storage of each text file, it cumulatively takes up approximately 71G of space. However, each individual file is smaller

**Comment by LemonQC** [comment]
@madeleinegrunde Ok, I see. You save the feature in txt and I can transfer it into h5 or other format. It's a great work!!!

**Comment by madeleinegrunde** [comment]
Yep! We store the questions as text, but feel free to transform the data however you like. h5 files of the video features can be found in [this folder](https://drive.google.com/drive/folders/1c51H6rxGHcc8en_sboFxH7Oqb_SVb2oQ).

**Comment by LemonQC** [comment]
Many thanks
