### ISSUE TITLE
Only tgif-qa dataset?

### ISSUE THREAD

**Issue by ByZ0e** [madeleinegrunde/AGQA_baselines_code#2]
Hi,
I'm wondering if these are the baselines only used for the TGIF-QA benchmark? How to start training or evaluation on the Action Genome Question Answering (AGQA) dataset?

**Comment by madeleinegrunde** [comment]
Hi,

Thank you for your question. We have adapted the baselines original code
for TGIF-QA to work for AGQA. The updated code files include these changes
that allow for the baselines to run using AGQA.

All the best,
Madeleine

**Comment by madeleinegrunde** [comment]
I see now where I think the confusion arose. The features are still labeled
their original file names, so they say TGIF, when in fact they include the
AGQA video features. I will update the README to clarify.

Thanks,
Madeleine

**Comment by ByZ0e** [comment]
Thanks for your reply. The file names are indeed a little bit confused me.
