### ISSUE TITLE
Training time consumption comparison among three baselines

### ISSUE THREAD

**Issue by AlyssaYoung** [madeleinegrunde/AGQA_baselines_code#4]
Thanks for providing the AGQA dataset and the exciting insights!

I have also trained these three baselines on my unpublished dataset which was collected by myself. I found that the official HME code needed too much time for one iteration and required much more time comsumption to achieve a good performance than the other two methods. I wonder whether you have also encountered this problem.

**Comment by madeleinegrunde** [comment]
Hi, 

Thank you for reaching out. Yes, we encountered a similar problem that the HME code required much more time than the other two models. Our solution was to let it run for a longer amount of time, despite it being computationally intensive. We saved copies of the model and validated more frequently than the original code to compensate for the long processing time.

**Comment by AlyssaYoung** [comment]
Thanks for your reply. How many GPUs and how much time did you use to achieve the results in the paper?

**Comment by madeleinegrunde** [comment]
Hi Alyssa,

We used 1 GPU, and if I remember correctly approximately 1 week.

**Comment by AlyssaYoung** [comment]
I got it! Thank you very much for your reply!
